<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>b50e9ad8-2ae3-43ca-a708-220a5090e2d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pagination > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='pagination']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05d863e5-1b5b-4d79-b5d5-9969fe2b963b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>applicant/vacancy/list/-1?size=10&amp;sc=validDateFrom&amp;sd=desc&amp;page=2</value>
      <webElementGuid>6aecf2e8-ecfe-407b-ab55-af1dafff9ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>87d513d4-2d78-4fce-9435-b7d9701aa2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagination&quot;)/li[4]/a[1]</value>
      <webElementGuid>4b580565-6ea1-4810-90f8-ba98ee99a345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pagination']/li[4]/a</value>
      <webElementGuid>2c7520c3-c89c-4b81-bff0-644835f23f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>922f79c4-d0a5-4f5e-bf51-7577a7527f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/following::a[1]</value>
      <webElementGuid>9a4e0206-149e-4d2f-a4e5-dfc7f7833972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/following::a[1]</value>
      <webElementGuid>705fb294-ed19-4ea4-8443-2459101d8017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='»'])[1]/preceding::a[1]</value>
      <webElementGuid>40f0ed2a-50bc-46dc-b554-18a9372d64eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last'])[1]/preceding::a[2]</value>
      <webElementGuid>0fa46756-3a08-4c3f-8277-fb6229d73cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'applicant/vacancy/list/-1?size=10&amp;sc=validDateFrom&amp;sd=desc&amp;page=2')]</value>
      <webElementGuid>4e5180ea-bf28-455e-a2d4-8223ab5fc926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[4]/a</value>
      <webElementGuid>187572f3-1399-463d-8bfd-afbe5c22c0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'applicant/vacancy/list/-1?size=10&amp;sc=validDateFrom&amp;sd=desc&amp;page=2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>3d0c20aa-543e-4b4f-9653-272a96f90ee1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
