<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Karir</name>
   <tag></tag>
   <elementGuidId>a76c4408-836d-4425-8de2-624092edfe95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Karir')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c91d040-efed-4080-b041-1d08e0700d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://recruitment.fifgroup.co.id/erecruitment/applicant/home?_gl=1*k23tzg*_ga*ODUwOTM5NjQ5LjE3MDgyNDA5OTI.*_ga_21M28N9CND*MTcwODI0MDk5Mi4xLjEuMTcwODI0MTE1NC42MC4wLjA.</value>
      <webElementGuid>e9cdca54-f0b6-460c-b136-39a157079265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karir</value>
      <webElementGuid>4a1f7274-e78f-4742-b03a-a7d1a09c0c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;footer&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm&quot;]/ul[@class=&quot;footer-item&quot;]/li[1]/a[1]</value>
      <webElementGuid>e00fe0cf-9b7b-4608-8fe9-59b68c328491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Karir')]</value>
      <webElementGuid>d8c33927-9f54-4e06-98ec-62c27339b22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTHER LINK'])[1]/following::a[1]</value>
      <webElementGuid>f286f528-1758-4106-b997-cf105e3b4ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontak Kami'])[1]/preceding::a[1]</value>
      <webElementGuid>477dd8e5-0490-429f-abeb-86184ea489a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Mitra'])[1]/preceding::a[2]</value>
      <webElementGuid>eba7c744-7e1f-4436-9314-b687e80b1ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karir']/parent::*</value>
      <webElementGuid>1d4fb9d6-47ca-451e-bae2-b2df644b94aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://recruitment.fifgroup.co.id/erecruitment/applicant/home?_gl=1*k23tzg*_ga*ODUwOTM5NjQ5LjE3MDgyNDA5OTI.*_ga_21M28N9CND*MTcwODI0MDk5Mi4xLjEuMTcwODI0MTE1NC42MC4wLjA.')]</value>
      <webElementGuid>4796a068-1e0f-4914-ba76-16b8f761ff2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul[2]/li/a</value>
      <webElementGuid>9a752c30-9583-46c3-a267-af5a17cc184d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://recruitment.fifgroup.co.id/erecruitment/applicant/home?_gl=1*k23tzg*_ga*ODUwOTM5NjQ5LjE3MDgyNDA5OTI.*_ga_21M28N9CND*MTcwODI0MDk5Mi4xLjEuMTcwODI0MTE1NC42MC4wLjA.' and (text() = 'Karir' or . = 'Karir')]</value>
      <webElementGuid>31453fd6-93eb-4d70-b278-2d1fd9ab35ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
